# Usage
#   Start:          docker compose up
#   Stop:           docker compose down

name: bloom-electric-test

services:
  electric:
    container_name: electric-test
    image: electricsql/electric:0.9.2
    # image: electricsql/electric:0.9.0
    # image: electricsql/electric:0.8
    init: true
    environment:
      DATABASE_URL: postgresql://postgres:postgres@host.docker.internal:44322/postgres
      PG_PROXY_PASSWORD: proxy_password
      ELECTRIC_WRITE_TO_PG_MODE: direct_writes
      AUTH_MODE: secure
      AUTH_JWT_ALG: HS256
      AUTH_JWT_KEY: super-secret-jwt-token-with-at-least-32-characters-long
    ports:
      - 5133:5133
      - 65432:65432
