import { app, BrowserWindow, ipcMain } from "electron";
import auth from "./auth";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

// import { LIB_VERSION } from 'electric-sql/version';
// import { makeElectricContext, useLiveQuery } from 'electric-sql/react';
// import { genUUID, uniqueTabId } from 'electric-sql/util';
// import { ElectricDatabase, electrify } from 'electric-sql/wa-sqlite';

// import { Electric, Scans as Scan, schema } from '../generated/client';

import Database from "better-sqlite3";
import { electrify } from "electric-sql/node";

// Import your generated database schema.
import { schema } from "./generated/client";

// Define your config with at least an auth token.
// See Usage -> Authentication for more details.
const config = {
  auth: auth,
};

// Create the better-sqlite3 database connection. The first
// argument is your database name. Changing this will
// create/use a new local database file.
const conn = new Database(
  "/Users/djbutler/dev/bloom-desktop-pilot/desktop-sync/example.db"
);

// Follow the library recommendation to enable WAL mode to
// increase performance. As per:
// https://github.com/WiseLibs/better-sqlite3/blob/master/docs/performance.md
conn.pragma("journal_mode = WAL");

electrify(conn, schema, config)
  .then(async (electric) => {
    // Use your electrified database here.
    console.log("Connected to the database");
    const { db } = electric;

    // Resolves when the shape subscription has been established.
    const shape = await db.scans.sync({ include: { phenotypers: true } });
    // Resolves when the data has been synced into the local database.
    await shape.synced;

    // Subscribe to data changes.
    electric.notifier.subscribeToDataChanges((changeNotification) => {
      changeNotification.dbName;
      changeNotification.changes.map((change) => {
        console.log(`table ${change.qualifiedTablename} changed`);
        console.log(`rows ${change.rowids} changed`);
      });
    });

    // set up callbacks
    ipcMain.handle("scans:get-all", async () => {
      const scans = await db.scans.findMany();
      return scans;
    });

    db.phenotypers
      .sync()
      .then(() => {
        db.phenotypers
          .findMany()
          .then((results) => {
            console.log("results from db.phenotypers.findMany() ->");
            console.log(results);
          })
          .catch((err) => {
            console.error("error calling db.phenotypers.findMany() ->");
            console.error(err);
          });
      })
      .catch((err) => {
        console.error("error calling db.phenotypers.sync() ->");
        console.error(err);
      });
  })
  .catch((err) => {
    console.error("error calling electrify(conn, schema, config) ->");
    console.error(err);
  });
